from enum import Enum


class OpCode(Enum):
    PUSHINT = "PUSHINT"
    PUSHBOOL = "PUSHBOOL"
    LVAL = "LVAL"
    RVALINT = "RVALINT"
    RVALBOOL = "RVALBOOL"
    ASSINT = "ASSINT"
    ASSBOOL = "ASSBOOL"
    ADD = "ADD"
    SUB = "SUB"
    EQBOOL = "EQBOOL"
    EQINT = "EQINT"
    LTINT = "LTINT"
    DECL = "DECL"
    POP = "POP"
    BRF = "BRF"
    BRA = "BRA"
    WRITEINT = "WRITEINT"
    WRITEBOOL = "WRITEBOOL"
    LINK = "LINK"
    UNLINK = "UNLINK"
    RTS = "RTS"
    BSR = "BSR"
    END = "END"
    LABEL = "LABEL"
    NEG = "NEG"
    NOT = "NOT"
    OR = "OR"
    LEINT = "LEINT"
    MULT = "MULT"
    DIV = "DIV"
    AND = "AND"
